version: '3.8'
services:
  ui:
    build: ui
    volumes:
      - ./ui:/usr/src/ui
      - /usr/src/ui/node_modules
    ports:
      - "3001:3000"
    tty: true
  api:
    build: api
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./api/.env
  db:
    image: mysql:5.7.31
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    env_file:
      - ./db/.env
